progress

diff --git a/.github/workflows/style.yml b/.github/workflows/style.yml
--- a/.github/workflows/style.yml
+++ b/.github/workflows/style.yml
@@ -1,7 +1,16 @@
 name: Style & License Header Check
 description: Check the formatting. Use "mvn com.spotify.fmt:fmt-maven-plugin:format" to format the code.
 
-on: [pull_request, merge_group]
+on:
+  pull_request:
+    branches:
+      - develop
+      - master
+  merge_group:
+
+env:
+  LATEST_BRANCH_NAME: develop
+  FINAL_BRANCH_NAME: master
 
 jobs:
   check-formatting:
@@ -26,3 +35,37 @@ jobs:
 
       - name: Check Javadoc
         run: mvn -B javadoc:aggregate -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
+
+
+      - name: SNAPSHOT version integrity check on every other branch than master
+        if: ${{ github.base_ref != env.FINAL_BRANCH_NAME }}
+        run: |
+          mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -q -- '-SNAPSHOT$'
+
+      - name: Ensure the proposed new version is higher than the latest version
+        run: |
+          PROPOSED_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version)"
+          TMP_POM=$(mktemp)
+          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+                -H "Accept: application/vnd.github.v3.raw" \
+                -O \
+                https://api.github.com/repos/${{ github.repository }}/contents/pom.xml?ref=${{ github.base_ref }}
+                -o "$TMP_POM"
+          LATEST_VERSION=$(mvn -f "$TMP_POM" org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version)
+          rm "$TMP_POM"
+          
+          # did the version not change? if not: master fails, other branches: ok      
+          if [ "$LATEST_VERSION" == "$PROPOSED_VERSION" ]; then
+            if [ "${{ github.base_ref }}" != "${{ env.FINAL_BRANCH_NAME }}" ]; then
+              exit 0
+            else
+              exit 1
+            fi
+          fi
+          
+          # is the new version higher? hint: does not handle 0.1.3-alpha versions.. just numbers! 
+          if [ "$(printf "%s\n%s" "$PROPOSED_VERSION" "$LATEST_VERSION" | sort -V | head -n1)" = "$PROPOSED_VERSION" ]; then
+              echo "Proposed new version is lower than the latest version!"
+              echo "$PROPOSED_VERSION <= $LATEST_VERSION"
+              exit 1
+          fi
